### ISSUE TITLE
Issue creating a subscription

### ISSUE THREAD

**Issue by emacadie** [agorapulse/grails-recurly#3]
I am working with a Grails 2.1.0 app, trying to integrate the plugin, version 2.0.1. When I try to create a RecurlySubscription, I get this:
groovy.lang.MissingPropertyException: No such property: account for class: grails.plugin.recurly.RecurlySubscription
    at grails.plugin.recurly.processors.RecurlySubscriptionProcessor.checkConstraints(RecurlySubscriptionProcessor.groovy:35)
    at grails.plugin.recurly.helpers.RecurlyProcessor.findErrors(RecurlyProcessor.groovy:43)
    at grails.plugin.recurly.helpers.ConstraintsValidator.validate(ConstraintsValidator.groovy:17)
    at grails.plugin.recurly.processors.RecurlySubscriptionProcessor.create(RecurlySubscriptionProcessor.groovy:45)
    at grails.plugin.recurly.RecurlyService.createSubscription(RecurlyService.groovy:148)

I have tried it two ways:
RecurlySubscription.create( rSub )
and
recurlyService.createSubscription( rSub )
and in the shell, and each time I get that error.

Any suggestions?

**Comment by benorama** [comment]
Have you tried latest version (v2.1.3)?

**Comment by emacadie** [comment]
Thanks for the quick response. (It's 3 AM here in the USA, so I might not be doing too many more real-time responses).
I tried again with 2.1.3, and got the same thing.
Here is what I typed on the shell:
import grails.plugin.recurly.*

recurlyService = ctx.getBean('recurlyService')

account = new RecurlyAccount(
userName: '',
firstName: 'Verenaa',
lastName: 'Examplea',
accountCode: '5',
email: 'some@example.com',
companyName: 'ACME'
)
recurlyService.createAccount(account)
rSub = new RecurlySubscription()
rSub.accountCode = account.accountCode
rSub.quantity = 1
recurlyService.createSubscription( rSub )

And I still got:
ERROR groovy.lang.MissingPropertyException:
No such property: account for class: grails.plugin.recurly.RecurlySubscription

**Comment by emacadie** [comment]
FYI: I can see the account in the Recurly console on the website, so the accounts are being created.

**Comment by benorama** [comment]
Indeed, there is some issue when creating subscriptions.
This is a plugin that we have inherited, we did several fixes and changes to make it compatible with the latest APIs, but we create subscription with RecurlyJS, we don't use subscriptions APIs. 
So this part of the code was not really tested. Sorry for that.

I'll have a look on this when I have some free time (not during the following days).
Have you tried RecurlyJS to handle subscriptions on the client-side?

**Comment by emacadie** [comment]
Thanks for the response.

Are you using your Groovy wrapper for RecurlyJS, and if so, are there any examples?

**Comment by benorama** [comment]
We are currently migrating for RecurlyJS V2 to RecurlyJS V3. So it's a work in progress.
Here the link to the docs : https://js.recurly.com

**Comment by benorama** [comment]
FYI, we have upgraded the plugin to be compatible with RecurlyJS V3 and fixed some issue on subscription processing.
